# 按照要求发布版本时候，触发这个脚本，自动创建一个release
name: Auto Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  trigger-build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Trigger Build All
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-all.yml',
              ref: 'main',
              inputs: {
                release_tag: '${{ steps.get_version.outputs.VERSION }}'
              }
            })