# 构建 macOS 桌面版 (Avalonia UI)
name: Build macOS Desktop (Avalonia UI)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - main

env:
  OutputArch: "macos-x64"
  OutputArchArm: "macos-arm64"
  OutputPath64: "${{ github.workspace }}/OfficeAssistant/bin/Release/macos-x64"
  OutputPathArm64: "${{ github.workspace }}/OfficeAssistant/bin/Release/macos-arm64"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '8.0.x'

    - name: Get Version
      id: version
      shell: bash
      run: |
        version=$(grep -m1 '<Version>' OfficeAssistant/OfficeAssistant.csproj | awk -F'[<>]' '{print $3}')
        echo "version=$version" >> $GITHUB_OUTPUT

    # 构建所有版本
    - name: Build All Versions
      run: |
        CommonParams=(
          "-c" "Release"
          "--self-contained" "true"
          "-p:PublishSingleFile=true"
          "-p:EnableCompressionInSingleFile=true"
          "-p:DebugType=None"
          "-p:DebugSymbols=false"
          "-p:UseAppHost=true"
          "-p:CreatePackage=true"
        )
        
        # x64 版本
        dotnet publish OfficeAssistant/OfficeAssistant.csproj \
          "${CommonParams[@]}" \
          -r osx-x64 \
          -o "${{ env.OutputPath64 }}"
        
        # ARM64 版本
        dotnet publish OfficeAssistant/OfficeAssistant.csproj \
          "${CommonParams[@]}" \
          -r osx-arm64 \
          -o "${{ env.OutputPathArm64 }}"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: OfficeAssistant-macOS-v${{ steps.version.outputs.version }}
        path: |
          ${{ github.workspace }}/OfficeAssistant/bin/Release/macos*
        if-no-files-found: error

    # 打包发布文件（仅在发布时执行）
    - name: Prepare Release Packages
      if: github.event.inputs.release_tag != ''
      run: |
        # 安装必要工具
        brew install create-dmg imagemagick

        # 准备图标
        if [ ! -f "OfficeAssistant/Resources/icon.icns" ]; then
          convert OfficeAssistant/Resources/icon.png OfficeAssistant/Resources/icon.icns || true
        fi

        # 设置脚本权限
        chmod 755 scripts/package-*.sh

        # 创建 DMG
        ./scripts/package-osx.sh "${{ env.OutputArch }}" "${{ env.OutputPath64 }}" "${{ steps.version.outputs.version }}"
        ./scripts/package-osx.sh "${{ env.OutputArchArm }}" "${{ env.OutputPathArm64 }}" "${{ steps.version.outputs.version }}"

        # 创建 ZIP
        ./scripts/package-release-zip.sh "${{ env.OutputArch }}" "${{ env.OutputPath64 }}" "${{ steps.version.outputs.version }}"
        ./scripts/package-release-zip.sh "${{ env.OutputArchArm }}" "${{ env.OutputPathArm64 }}" "${{ steps.version.outputs.version }}"

    - name: Create Release
      if: github.event.inputs.release_tag != ''
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        files: |
          OfficeAssistant-macos*.dmg
          OfficeAssistant-macos*.zip
        prerelease: true
        generate_release_notes: true
