name: .NET Core Desktop  # 工作流名称

on:  # 触发工作流的事件
  push:  # 当代码推送时触发
    branches: [ "main" ]  # 仅在 main 分支上触发
  pull_request:  # 当创建 Pull Request 时触发
    branches: [ "main" ]  # 仅针对 main 分支的 PR

jobs:  # 定义工作流中的作业
  build-windows:  # Windows 构建作业
    strategy:
      matrix:
        configuration: [Release]  # 只构建 Release 版本

    runs-on: windows-latest  # 在最新版本的 Windows 运行器上运行

    env:  # 环境变量设置
      Solution_Name: OfficeAssistant.sln  # 解决方案文件名

    steps:  # 构建步骤
    - name: Checkout  # 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的版本历史

    - name: Install .NET Core  # 安装 .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # 使用 .NET 8.0 版本

    - name: Restore dependencies  # 还原项目依赖
      run: dotnet restore

    - name: Build (Framework-dependent)  # 构建依赖框架的版本
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Build (Self-contained)  # 构建自包含版本
      run: dotnet publish OfficeAssistant/OfficeAssistant.csproj --configuration ${{ matrix.configuration }} --no-restore -r win-x64 --self-contained true

    - name: Upload Framework-dependent artifacts  # 上传依赖框架的构建产物
      uses: actions/upload-artifact@v4
      with:
        name: OfficeAssistant-Windows-Framework-dependent  # 构建产物名称
        path: |  # 构建产物路径
          OfficeAssistant/bin/${{ matrix.configuration }}/net8.0/**/*

    - name: Upload Self-contained artifacts  # 上传自包含的构建产物
      uses: actions/upload-artifact@v4
      with:
        name: OfficeAssistant-Windows-Self-contained  # 构建产物名称
        path: |  # 构建产物路径
          OfficeAssistant/bin/${{ matrix.configuration }}/net8.0/win-x64/**/*

  build-macos:  # macOS 构建作业
    strategy:
      matrix:
        configuration: [Release]  # 只构建 Release 版本
    
    runs-on: macos-latest  # 在最新版本的 macOS 运行器上运行

    env:  # 环境变量设置
      Solution_Name: OfficeAssistant.sln  # 解决方案文件名

    steps:  # 构建步骤
    - name: Checkout  # 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的版本历史

    - name: Install .NET Core  # 安装 .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # 使用 .NET 8.0 版本

    - name: Restore dependencies  # 还原项目依赖
      run: dotnet restore

    - name: Build  # 构建项目
      run: dotnet publish OfficeAssistant/OfficeAssistant.csproj --configuration ${{ matrix.configuration }} --no-restore -r osx-x64 --self-contained true
      # -r osx-x64: 指定目标平台为 macOS x64
      # --self-contained true: 包含所有运行时依赖

    - name: Upload build artifacts  # 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: OfficeAssistant-macOS-${{ matrix.configuration }}  # macOS 构建产物名称
        path: |  # 构建产物路径
          OfficeAssistant/bin/${{ matrix.configuration }}/net8.0/osx-x64/**/*
